#I found this in docker hub just by searching python
FROM python:3.12-slim 

#just setting the working folder in the container
WORKDIR /calcapp

#here we copy the content of BE folder into /app folder in the docker container
COPY . /calcapp/

#Using --no-cache-dir during package installation in a Dockerfile
#helps keep the Docker images smaller by avoiding the storage of unnecessary cached files.
# Install dependencies from requirements.txt and requirements-test.txt
RUN pip install --no-cache-dir -r requirements.txt



# Set the entrypoint to python, so it runs the script
ENTRYPOINT ["python", "calculator_rest_service.py", "--rest"]


