# Stage 1: Build
FROM python:3.12-slim as build

WORKDIR /app

COPY BE/requirements.txt BE/requirements-test.txt ./
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install --no-cache-dir -r requirements-test.txt

COPY BE/ .

# Stage 2: Runtime
FROM python:3.12-slim

WORKDIR /app

# Copy only necessary files from the build stage
COPY --from=build /app /app

# Set the entrypoint to run the application
ENTRYPOINT ["python", "calculator.py"]

# Provide default arguments to the entrypoint
CMD ["--multiply", "3", "7"]
