# GP = Good Practice
name: Calculator Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      PYTHONPATH: ./BE # Set PYTHONPATH to the BE directory for faster access and enhanced readability (GP)

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Cache Python dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip 
          key: ${{ runner.os }}-pip-${{ hashFiles('BE/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        working-directory: BE
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.20.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Start Docker Compose Services
        run: |
          docker-compose -f ./docker-compose.yml up -d # ensure that docker-compose is in the root folder

      - name: Start REST API
        working-directory: BE
        run: |
          nohup python calculator.py --rest & 
          sleep 10

      - name: Run Tests
        run: |
          python -m pytest -s -v --maxfail=1 --exitfirst --strict-markers --junit-xml=ci_report.xml
        continue-on-error: false

      - name: Upload Test Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ci-pytest-report
          path: ci_report.xml

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        if: always()
        with:
          report_paths: "**/*.xml"

      - name: Log in to Azure Container Registry
        uses: docker/login-action@v2
        with:
          registry: judevops.azurecr.io
          username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
          password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}

      - name: Build Docker Image
        working-directory: BE
        run: |
          docker build -t ali_kouravand_calculator_ci:${{ github.sha }} .

      - name: Tag Docker Image
        run: |
          docker tag ali_kouravand_calculator_ci:${{ github.sha }} judevops.azurecr.io/ali_kouravand_calculator_ci:${{ github.sha }}

      - name: Push Docker Image
        run: |
          docker push judevops.azurecr.io/ali_kouravand_calculator_ci:${{ github.sha }}

      - name: Run Calculator
        run: |
          docker run -d judevops.azurecr.io/ali_kouravand_calculator_ci:${{ github.sha }} --add 1 7

      - name: Docker Cleanup # (GP) Clean up my disc space
        run: |
          docker system prune -af
