name: Calculator Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Cache Python dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('BE/requirements.txt') }}-${{ hashFiles('BE/requirements-test.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          cd BE
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-test.txt

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$(pwd)/BE" >> $GITHUB_ENV

      - name: Run Tests
        run: |
          python -m pytest -s -v --maxfail=1 --exitfirst --strict-markers
        continue-on-error: false

      - name: Log in to Azure Container Registry
        uses: docker/login-action@v2
        with:
          registry: judevops.azurecr.io
          username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
          password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}

      - name: Build Docker Image
        run: |
          cd BE
          docker build -t ali_kouravand_calculator_ci:6.0 .

      - name: Tag Docker Image
        run: |
          docker tag ali_kouravand_calculator_ci:6.0 judevops.azurecr.io/ali_kouravand_calculator_ci:6.0

      - name: Push Docker Image
        run: |
          docker push judevops.azurecr.io/ali_kouravand_calculator_ci:6.0

      - name: Run Calculator
        run: |
          docker run judevops.azurecr.io/ali_kouravand_calculator_ci:6.0 --add 1 7
